### ISSUE TITLE
Optimal Solution?

### ISSUE THREAD

**Issue by h01m3s** [cisc3410/1-search#3]
Hi Professor Levitan, @rivlev 

Do you want exact solutions as your "solutions_done.txt"?

Or other possible path is ok?

**Comment by rivlev** [comment]
Another path is okay. I've been told that there is another optimal solution for at least one of the problems. If it's the same length as the one in solutions_done.txt, and you've checked that it works, then it's okay. Note that the travis check may fail but I will look at it manually.
