### ISSUE TITLE
Not showing up on Travis

### ISSUE THREAD

**Issue by myang310** [cisc3410/1-search#4]
My repo isn't showing up on Travis CI. Should I just contact their support team or is this something to be done on my end? @rivlev

**Comment by myang310** [comment]
Also to clarify, it's not even showing up as an option to turn on, unlike ``cisc3410/0-get-started-myang310``

**Comment by rivlev** [comment]
I found it here https://www.travis-ci.com/cisc3410/1-search-myang310
and activated it for you

**Comment by h01m3s** [comment]
@rivlev  I got the same issue, could you activate it for me?
