### ISSUE TITLE
error: use of undeclared identifier 'State'

### ISSUE THREAD

**Issue by MichaelGregg** [cisc3410/1-search#5]
In lines 84 89 and 93 of this code:
![screen shot 2017-09-25 at 10 51 19 pm](https://user-images.githubusercontent.com/25493211/30840321-96060bb0-a244-11e7-9d99-23fb06520832.png)
I get the same error messages:
![screen shot 2017-09-25 at 10 56 43 pm](https://user-images.githubusercontent.com/25493211/30840375-d9fe1ad8-a244-11e7-8e29-de7203dda693.png)
@rivlev

**Comment by rivlev** [comment]
Did you delete the line before the declaration of the Problem class that says ```template <class State>```?

**Comment by MichaelGregg** [comment]
No it is still there:
![screen shot 2017-09-26 at 12 32 42 am](https://user-images.githubusercontent.com/25493211/30842725-574402ca-a252-11e7-808d-9beda55bb355.png)
@rivlev

**Comment by rivlev** [comment]
Please push your current code to github (add, commit, push) and I will take a look. Please @mention me in the commit message.

**Comment by MichaelGregg** [comment]
ok i pushed it and mentioned you in the commit message @rivlev
