### ISSUE TITLE
Travis CI not picking up branches

### ISSUE THREAD

**Issue by myang310** [cisc3410/1-search#6]
After activating the new repo on Travis CI, it doesn't show any of my new PRs or branches. Not sure how to go about correcting this. @rivlev

**Comment by rivlev** [comment]
Make a trivial change to one of your code files and push a new commit. It only knows about commits that happen after it was activated.

Please close if this works.

**Comment by h01m3s** [comment]
@rivlev  my problem was fixed by pushing a new commit.

**Comment by myang310** [comment]
@rivlev solved. thanks for the suggestion!
