### ISSUE TITLE
Outputs for puzze 2 not matching

### ISSUE THREAD

**Issue by Russ226** [cisc3410/1-search#7]
My puzzle 2's outputs do not match solutions_done.txt file's outputs but they both take the same amount of moves to finish. Would the output still be an acceptable answer?

**solutions_done.txt:**
START right up left down down right up right up left down left up right right down down left up left up 

**solutions.out:**
START right down left up right right down left left up right up right down left down right up up left left

@rivlev

**Comment by rivlev** [comment]
Please see #3

**Comment by Russ226** [comment]
Thank you.
