### ISSUE TITLE
Errors in NPuzzle and Problem

### ISSUE THREAD

**Issue by MichaelGregg** [cisc3410/1-search#9]
I am now getting the following errors, among others:
In NPuzzle:
![screen shot 2017-09-26 at 11 42 56 pm](https://user-images.githubusercontent.com/25493211/30894877-811d28b6-a314-11e7-9e86-b1c1d4e0d52d.png)
Here is the seciton of code containing line 62:
In Problem:
![screen shot 2017-09-26 at 11 45 20 pm](https://user-images.githubusercontent.com/25493211/30894920-ccac92da-a314-11e7-8843-d9ae05e8593b.png)
Here is the section of code containing line 48:
@rivlev 

(edited by @rivlev: please do not post screenshots of code)

**Comment by rivlev** [comment]
It looks like you have a stray bracket or unclosed parentheses that is messing up your code structure. That is what was wrong with it before. You need to go through it in a good editor to find the syntax error.

Please do not post screenshots of code. If you want me to look at your code, make sure it is synced to your Github account so I can view it in your private repository online.
